apiVersion: v1
kind: Service
metadata:
  namespace: linkerd-ns
  name: namerd-ctl
spec:
  selector:
    app: namerd

  type: LoadBalancer
  ports:
    - name: ctl
      port: 80
      targetPort: 4180

    - name: admin
      port: 9990
